/**
 * Preference public API
 * Preference public API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import BadRequestError from './model/BadRequestError';
import Movie from './model/Movie';
import MovieAllOf from './model/MovieAllOf';
import MovieBase from './model/MovieBase';
import MoviesResponse from './model/MoviesResponse';
import MovieApi from './api/MovieApi';


/**
* Preference public API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PreferencePublicApi = require('index'); // See note below*.
* var xxxSvc = new PreferencePublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PreferencePublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PreferencePublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PreferencePublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BadRequestError model constructor.
     * @property {module:model/BadRequestError}
     */
    BadRequestError,

    /**
     * The Movie model constructor.
     * @property {module:model/Movie}
     */
    Movie,

    /**
     * The MovieAllOf model constructor.
     * @property {module:model/MovieAllOf}
     */
    MovieAllOf,

    /**
     * The MovieBase model constructor.
     * @property {module:model/MovieBase}
     */
    MovieBase,

    /**
     * The MoviesResponse model constructor.
     * @property {module:model/MoviesResponse}
     */
    MoviesResponse,

    /**
    * The MovieApi service constructor.
    * @property {module:api/MovieApi}
    */
    MovieApi
};
