/**
 * Preference public API
 * Preference public API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BadRequestError model module.
 * @module model/BadRequestError
 * @version 0.1.0
 */
class BadRequestError {
    /**
     * Constructs a new <code>BadRequestError</code>.
     * @alias module:model/BadRequestError
     */
    constructor() { 
        
        BadRequestError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BadRequestError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BadRequestError} obj Optional instance to populate.
     * @return {module:model/BadRequestError} The populated <code>BadRequestError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BadRequestError();

            if (data.hasOwnProperty('messages')) {
                obj['messages'] = ApiClient.convertToType(data['messages'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BadRequestError</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BadRequestError</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['messages'])) {
            throw new Error("Expected the field `messages` to be an array in the JSON data but got " + data['messages']);
        }

        return true;
    }


}



/**
 * List of error messages
 * @member {Array.<String>} messages
 */
BadRequestError.prototype['messages'] = undefined;






export default BadRequestError;

