/**
 * Preference public API
 * Preference public API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Movie from './Movie';

/**
 * The MoviesResponse model module.
 * @module model/MoviesResponse
 * @version 0.1.0
 */
class MoviesResponse {
    /**
     * Constructs a new <code>MoviesResponse</code>.
     * @alias module:model/MoviesResponse
     */
    constructor() { 
        
        MoviesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MoviesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MoviesResponse} obj Optional instance to populate.
     * @return {module:model/MoviesResponse} The populated <code>MoviesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MoviesResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Movie]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MoviesResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MoviesResponse</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                Movie.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Movie>} data
 */
MoviesResponse.prototype['data'] = undefined;

/**
 * @member {Number} total
 */
MoviesResponse.prototype['total'] = undefined;

/**
 * @member {Number} offset
 */
MoviesResponse.prototype['offset'] = undefined;

/**
 * @member {Number} limit
 */
MoviesResponse.prototype['limit'] = undefined;






export default MoviesResponse;

